---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        entry: yamllint --strict -c .hooks/linters/.yaml-lint.yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        files: \.(json|md|yaml|yml)$

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: script-must-have-extension
        name: Ensure shell scripts end with .sh
        types: [shell]
      - id: shellcheck
      - id: shfmt

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: golangci-lint
        args: ["--skip-files", "ttp*.go"]
      - id: go-critic
      - id: go-build
      - id: go-mod-tidy

  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: python -m nbconvert --ClearOutputPreprocessor.enabled=True --inplace
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        name: Run codespell
        description: Check spelling with codespell
        entry: |
          codespell -q 3 -L "aks,AKS,iterm" -q 3 -f
          -S ".git,.github,README.md,docs/*,tests/*,counterfit/*"
          --ignore-regex ".*ounterfit.*"
