---
name: Pre-Commit

on:
  pull_request:
  push:
    branches: [devopsy]

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2

      - name: Install python for pre-commit
        uses: actions/setup-python@v2
        with:
          python-version: "3"

      - name: Install pre-commit dependencies
        run: |
          brew install shellcheck \
            shfmt black pylint shellcheck

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
