#
# Test to run the Corrupted Replay Attack (CRA).
#
# Usage:
#
# conda activate counterfit
# ./cra_test.exp "$(uname)" 120

# Get os from cli input
set os [lindex $argv 0]

# Get seconds from cli input
set timeout [lindex $argv 1]

# Get terminal.py path from cli input
set termpy [lindex $argv 2]

if { $os == "Linux" } {
    spawn xvfb-run -a python $termpy
  } else {
    spawn python $termpy
  }

expect "counterfit>"
send "load art\r"
send "interact cart_pole\r"
send "use HopSkipJump\r"
send "set --max_eval 100 --init_eval 10 --init_size 10\r"
send "run\r"

expect eof;
