#
# Test to run the Initial State Perturbation Attack.
#
# Usage:
#
# conda activate counterfit
# ./ispa_test.exp "$(uname)" 120

# Get os from cli input
set os [lindex $argv 0]

# Get seconds from cli input
set timeout [lindex $argv 1]

# Get terminal.py path from cli input
set termpy [lindex $argv 2]

if { $os == "Linux" } {
    spawn xvfb-run -a python $termpy
  } else {
    spawn python $termpy
  }

expect "counterfit>"
send "set_target digits_keras\r"
expect "digits_keras>"
send "set_attack hop_skip_jump\r"
expect "success:"
send "run\r"
expect "success:"
send "show results\r"
expect "1/1"
send "exit counterfit\r"
send "y\r"
expect eof;
