#
# Test to run the Initial State Perturbation Attack.
#
# Usage:
#
# conda activate counterfit
# ./ispa_test.exp "$(uname)" 120

# Get os from cli input
set os [lindex $argv 0]

# Get seconds from cli input
set timeout [lindex $argv 1]

if { $os == "Linux" } {
    spawn xvfb-run -a python counterfit.py
  } else {
    spawn python counterfit.py
  }

expect "counterfit>"
send "load art\r"
send "interact cart_pole_initstate\r"
send "use HopSkipJump\r"
send "set --max_eval 100 --init_eval 10 --init_size 10\r"
send "run\r"

expect eof;
