---
name: Tests
on:
  pull_request:
  push:
    branches: [attackingRL]

env:
  PYTHON_VERSION: 3.8.8
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2
        with:
          ref: attackingRL

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-opengl xvfb

      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: counterfit
          auto-update-conda: true
          python-version: ${{ env.PYTHON_VERSION }}
          environment-file: environment.yml

      - name: Setup test environment
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Test install
        shell: bash -l {0}
        run: |
          echo 'exit counterfit' | xvfb-run -a python counterfit.py
          if [[ $? != 0 ]]; then
              echo "Install of counterfit failed!"
          fi

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Report failure
        uses: nashmaniac/create-issue-action@v1.1
        # Only report failures of pushes (PRs have are visible through the Checks section)
        # to the default branch
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          title: 🐛 Coverage report failed for ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: kind/bug
          body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
